spring:
  application:
    name: db-service

server:
  port: 8711


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8701/eureka/
  instance:
    hostname: localhost

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
      base-path: /    